services:
  # Institutional School Database (MySQL)
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: face_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Redis for Celery
  redis:
    image: redis:7.0-alpine
    container_name: redis-cache
    restart: always
    ports:
      - "6380:6379"


  # WAHA (WhatsApp HTTP API)
  waha:
    image: devlikeapro/waha
    container_name: waha
    restart: always
    environment:
      - WAHA_WEBHOOK_URL=http://host.docker.internal:8000/webhook/waha
      - WAHA_WEBHOOK_EVENTS=message
      - WAHA_API_KEY=visio_waha_secure_key_123
    ports:
      - "3001:3000"

volumes:
  mysql_data: